### PR TITLE
Bump rollup to 0.67.4

### PR DESCRIPTION
**Pull request by mnutt**
This builds off of @asakusuma's work in https://github.com/chadhietala/broccoli-rollup/commit/bd01ded588b8b680b02ceabde71b0a507f704b42 and gets the tests passing.

I believe that rollup's `experimentalCodeSplitting` output intentionally changed slightly, and the output seems consistent and working so I changed the tests that reference it.

### CODE REVIEW

**Comment by mnutt** [comment]
The failures in node 6 and node 8 seem to be around heimdalljs: 
```
return instrument('rollup', () => {
   ...
   return promise;
});
```
(https://github.com/chadhietala/broccoli-rollup/pull/42/files#diff-ed009b6b86b017532ef0489c77de5100L136)

```
(node:51677) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 1)
```

As far as I can tell, this seems to be inherent in how heimdall takes a callback, and if that callback throws or returns a promise rejection, that error ends up being handled asynchronously.

The only way I've figured out to fix this so far is to either a) not support node < 10 (undesirable) or b) use `heimdall.start` / `heimdall.stop` rather than `heimdall.node`.

**Comment by mnutt** [comment]
At this point the only build failure is due to `source-map` 0.7 and above only supporting node.js >= 8. I'm happy to roll back the dependency bump, but the `source-map` 0.7 release notes tout "massive performance gains" so it may be worth considering dropping node 6.x support?

**Comment by mnutt** [comment]
Hey @krisselden would you be able to weigh in on the node 6.x support?

**Comment by krisselden** [comment]
this is superseded by #44

**Pull request closed without merging**
