### PR TITLE
Bump rollup to 0.43

### PR DESCRIPTION
**Pull request by dwickern**
Fixes rollup/rollup#1385 which is blocking emberjs/ember-inspector#688

### CODE REVIEW

**Comment by stefanpenner** [comment]
@dwickern looks like the source-map output is slightly  different, mind correcting the tests? Then we can cut

**Comment by dwickern** [comment]
done

**Comment by stefanpenner** [comment]
released as v1.4.0 🎉

**Comment by stefanpenner** [comment]
this broke ember-data, and some other apps. Unpublished, will investigate...

**Comment by stefanpenner** [comment]
just a headsup @chadhietala  ^

**Pull request merged**
